apiVersion: virtualservers.coreweave.com/v1alpha1
kind: VirtualServer
metadata:
  name: invoke-ai-by-zeref
spec:
  region: ORD1
  os:
    type: linux
    enableUEFIBoot: false
  resources:
    gpu:
      type: RTX_A6000
      count: 1
    cpu:
      count: 3
    memory: 16Gi
  runStrategy: RerunOnFailure
  storage:
    root:
      size: 40Gi
      storageClassName: block-nvme-ord1
      source:
        pvc:
          namespace: vd-images
          name:  ubuntu2204-nvidia-515-43-04-1-docker-master-20220831-ord1
      volumeMode: Block
  users:
    - username: zeref
      password: dragoneel  
  network:
    public: true
    tcp:
      ports:
        - 22
        - 80
        - 443
  cloudInit: |
    # Write a simple script
    write_files:
    - content: |
        #!/bin/bash
        echo "Hello world!"
      path: $HOME/deploy.sh
      permissions: '0744'
      owner: zeref:zeref
    # Update packages
    package_update: true
    # Install packages
    packages:
      - curl
      - git
    # Run additional commands
    runcmd:
      - [df, -h]
      - [git, version]
      - [curl, --version ]
      - [bash, $HOME/deploy.sh]
  initializeRunning: true