apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vs-shared-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: block-nvme-ord1
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi